check:
    npm run type-check
    npm run format-check
    npm run lint
    npm run test:once

build:
    npm run build

format:
    npm run format

start:
    npm install
    npm run dev

setup:
    npm install

fix: 
    npm run lint:fix
