[package]
name = "clip-mash-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clip-mash-client = { path = "../rust-client" }
color-eyre = "0.6.3"
comfy-table = "7.1.1"
tokio = { version = "1.38.0", features = ["full"] }
