/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddVideosRequestOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "urls")]
    pub urls: Vec<String>,
}

impl AddVideosRequestOneOf1 {
    pub fn new(r#type: Type, urls: Vec<String>) -> AddVideosRequestOneOf1 {
        AddVideosRequestOneOf1 { r#type, urls }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "download")]
    Download,
}

impl Default for Type {
    fn default() -> Type {
        Self::Download
    }
}
