/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddVideosRequestOneOf {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "recurse")]
    pub recurse: bool,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AddVideosRequestOneOf {
    pub fn new(path: String, recurse: bool, r#type: Type) -> AddVideosRequestOneOf {
        AddVideosRequestOneOf {
            path,
            recurse,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "local")]
    Local,
}

impl Default for Type {
    fn default() -> Type {
        Self::Local
    }
}
