/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AddVideosRequest {
    #[serde(rename = "AddVideosRequest_oneOf")]
    AddVideosRequestOneOf(Box<models::AddVideosRequestOneOf>),
    #[serde(rename = "AddVideosRequest_oneOf_1")]
    AddVideosRequestOneOf1(Box<models::AddVideosRequestOneOf1>),
    #[serde(rename = "AddVideosRequest_oneOf_2")]
    AddVideosRequestOneOf2(Box<models::AddVideosRequestOneOf2>),
}

impl Default for AddVideosRequest {
    fn default() -> Self {
        Self::AddVideosRequestOneOf(Default::default())
    }
}
