/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddVideosRequestOneOf2 {
    #[serde(rename = "sceneIds")]
    pub scene_ids: Vec<i64>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AddVideosRequestOneOf2 {
    pub fn new(scene_ids: Vec<i64>, r#type: Type) -> AddVideosRequestOneOf2 {
        AddVideosRequestOneOf2 { scene_ids, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "stash")]
    Stash,
}

impl Default for Type {
    fn default() -> Type {
        Self::Stash
    }
}
