/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppVersion {
    #[serde(rename = "currentVersion")]
    pub current_version: String,
    #[serde(rename = "needsUpdate")]
    pub needs_update: bool,
    #[serde(rename = "newestVersion")]
    pub newest_version: String,
}

impl AppVersion {
    pub fn new(current_version: String, needs_update: bool, newest_version: String) -> AppVersion {
        AppVersion {
            current_version,
            needs_update,
            newest_version,
        }
    }
}
