/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Beats {
    #[serde(rename = "length")]
    pub length: f32,
    #[serde(rename = "offsets")]
    pub offsets: Vec<f32>,
}

impl Beats {
    pub fn new(length: f32, offsets: Vec<f32>) -> Beats {
        Beats { length, offsets }
    }
}
