/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ClipPickerOptions {
    #[serde(rename = "ClipPickerOptions_oneOf")]
    ClipPickerOptionsOneOf(Box<models::ClipPickerOptionsOneOf>),
    #[serde(rename = "ClipPickerOptions_oneOf_1")]
    ClipPickerOptionsOneOf1(Box<models::ClipPickerOptionsOneOf1>),
    #[serde(rename = "ClipPickerOptions_oneOf_2")]
    ClipPickerOptionsOneOf2(Box<models::ClipPickerOptionsOneOf2>),
    #[serde(rename = "ClipPickerOptions_oneOf_3")]
    ClipPickerOptionsOneOf3(Box<models::ClipPickerOptionsOneOf3>),
}

impl Default for ClipPickerOptions {
    fn default() -> Self {
        Self::ClipPickerOptionsOneOf(Default::default())
    }
}
