/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ClipLengthOptions {
    #[serde(rename = "ClipLengthOptions_oneOf")]
    ClipLengthOptionsOneOf(Box<models::ClipLengthOptionsOneOf>),
    #[serde(rename = "ClipLengthOptions_oneOf_1")]
    ClipLengthOptionsOneOf1(Box<models::ClipLengthOptionsOneOf1>),
}

impl Default for ClipLengthOptions {
    fn default() -> Self {
        Self::ClipLengthOptionsOneOf(Default::default())
    }
}
