/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipOptions {
    #[serde(rename = "clipPicker")]
    pub clip_picker: Box<models::ClipPickerOptions>,
    #[serde(rename = "order")]
    pub order: Box<models::ClipOrder>,
}

impl ClipOptions {
    pub fn new(clip_picker: models::ClipPickerOptions, order: models::ClipOrder) -> ClipOptions {
        ClipOptions {
            clip_picker: Box::new(clip_picker),
            order: Box::new(order),
        }
    }
}
