/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipOrderOneOf3 {
    #[serde(rename = "markerTitleGroups")]
    pub marker_title_groups: Vec<models::MarkerGroup>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ClipOrderOneOf3 {
    pub fn new(marker_title_groups: Vec<models::MarkerGroup>, r#type: Type) -> ClipOrderOneOf3 {
        ClipOrderOneOf3 {
            marker_title_groups,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fixed
    }
}
