/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipOrderOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ClipOrderOneOf1 {
    pub fn new(r#type: Type) -> ClipOrderOneOf1 {
        ClipOrderOneOf1 { r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "scene")]
    Scene,
}

impl Default for Type {
    fn default() -> Type {
        Self::Scene
    }
}
