/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ClipOrder {
    #[serde(rename = "ClipOrder_oneOf")]
    ClipOrderOneOf(Box<models::ClipOrderOneOf>),
    #[serde(rename = "ClipOrder_oneOf_1")]
    ClipOrderOneOf1(Box<models::ClipOrderOneOf1>),
    #[serde(rename = "ClipOrder_oneOf_2")]
    ClipOrderOneOf2(Box<models::ClipOrderOneOf2>),
    #[serde(rename = "ClipOrder_oneOf_3")]
    ClipOrderOneOf3(Box<models::ClipOrderOneOf3>),
}

impl Default for ClipOrder {
    fn default() -> Self {
        Self::ClipOrderOneOf(Default::default())
    }
}
