/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipPickerOptionsOneOf2 {
    #[serde(rename = "clipDuration")]
    pub clip_duration: f64,
    #[serde(rename = "divisors")]
    pub divisors: Vec<f64>,
    #[serde(
        rename = "length",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub length: Option<Option<f64>>,
    #[serde(
        rename = "minClipDuration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_clip_duration: Option<Option<f64>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ClipPickerOptionsOneOf2 {
    pub fn new(clip_duration: f64, divisors: Vec<f64>, r#type: Type) -> ClipPickerOptionsOneOf2 {
        ClipPickerOptionsOneOf2 {
            clip_duration,
            divisors,
            length: None,
            min_clip_duration: None,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "equalLength")]
    EqualLength,
}

impl Default for Type {
    fn default() -> Type {
        Self::EqualLength
    }
}
