/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInteractiveClipsBody {
    #[serde(rename = "clipDuration")]
    pub clip_duration: f64,
    #[serde(rename = "markerTitles")]
    pub marker_titles: Vec<String>,
    #[serde(rename = "order")]
    pub order: Box<models::ClipOrder>,
}

impl CreateInteractiveClipsBody {
    pub fn new(
        clip_duration: f64,
        marker_titles: Vec<String>,
        order: models::ClipOrder,
    ) -> CreateInteractiveClipsBody {
        CreateInteractiveClipsBody {
            clip_duration,
            marker_titles,
            order: Box::new(order),
        }
    }
}
