/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMarkerRequest {
    #[serde(rename = "createInStash")]
    pub create_in_stash: bool,
    #[serde(rename = "marker")]
    pub marker: Box<models::CreateMarker>,
}

impl CreateMarkerRequest {
    pub fn new(create_in_stash: bool, marker: models::CreateMarker) -> CreateMarkerRequest {
        CreateMarkerRequest {
            create_in_stash,
            marker: Box::new(marker),
        }
    }
}
