/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMarker {
    #[serde(
        rename = "createdOn",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_on: Option<Option<i64>>,
    #[serde(rename = "end")]
    pub end: f64,
    #[serde(rename = "indexWithinVideo")]
    pub index_within_video: i64,
    #[serde(
        rename = "markerStashId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub marker_stash_id: Option<Option<i64>>,
    #[serde(
        rename = "previewImagePath",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub preview_image_path: Option<Option<String>>,
    #[serde(rename = "start")]
    pub start: f64,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "videoId")]
    pub video_id: String,
    #[serde(rename = "videoInteractive")]
    pub video_interactive: bool,
}

impl CreateMarker {
    pub fn new(
        end: f64,
        index_within_video: i64,
        start: f64,
        title: String,
        video_id: String,
        video_interactive: bool,
    ) -> CreateMarker {
        CreateMarker {
            created_on: None,
            end,
            index_within_video,
            marker_stash_id: None,
            preview_image_path: None,
            start,
            title,
            video_id,
            video_interactive,
        }
    }
}
