/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBeatFunscriptBody {
    #[serde(rename = "songIds")]
    pub song_ids: Vec<i64>,
    #[serde(rename = "strokeType")]
    pub stroke_type: Box<models::StrokeType>,
}

impl CreateBeatFunscriptBody {
    pub fn new(song_ids: Vec<i64>, stroke_type: models::StrokeType) -> CreateBeatFunscriptBody {
        CreateBeatFunscriptBody {
            song_ids,
            stroke_type: Box::new(stroke_type),
        }
    }
}
