/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescriptionData {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "contentType")]
    pub content_type: String,
}

impl DescriptionData {
    pub fn new(body: String, content_type: String) -> DescriptionData {
        DescriptionData { body, content_type }
    }
}
