/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileSystemEntryOneOf1 {
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "fullPath")]
    pub full_path: String,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl FileSystemEntryOneOf1 {
    pub fn new(
        file_name: String,
        full_path: String,
        size: i64,
        r#type: Type,
    ) -> FileSystemEntryOneOf1 {
        FileSystemEntryOneOf1 {
            file_name,
            full_path,
            size,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
