/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FileSystemEntry {
    #[serde(rename = "FileSystemEntry_oneOf")]
    FileSystemEntryOneOf(Box<models::FileSystemEntryOneOf>),
    #[serde(rename = "FileSystemEntry_oneOf_1")]
    FileSystemEntryOneOf1(Box<models::FileSystemEntryOneOf1>),
}

impl Default for FileSystemEntry {
    fn default() -> Self {
        Self::FileSystemEntryOneOf(Default::default())
    }
}
