/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVideoDto {
    #[serde(rename = "markerCount")]
    pub marker_count: i32,
    #[serde(rename = "video")]
    pub video: Box<models::VideoDto>,
}

impl ListVideoDto {
    pub fn new(marker_count: i32, video: models::VideoDto) -> ListVideoDto {
        ListVideoDto {
            marker_count,
            video: Box::new(video),
        }
    }
}
