/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListFileEntriesResponse {
    #[serde(rename = "directory")]
    pub directory: String,
    #[serde(rename = "drives")]
    pub drives: Vec<String>,
    #[serde(rename = "entries")]
    pub entries: Vec<models::FileSystemEntry>,
}

impl ListFileEntriesResponse {
    pub fn new(
        directory: String,
        drives: Vec<String>,
        entries: Vec<models::FileSystemEntry>,
    ) -> ListFileEntriesResponse {
        ListFileEntriesResponse {
            directory,
            drives,
            entries,
        }
    }
}
