/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkerTitle {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "title")]
    pub title: String,
}

impl MarkerTitle {
    pub fn new(count: i32, title: String) -> MarkerTitle {
        MarkerTitle { count, title }
    }
}
