/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkerDtoPage {
    #[serde(rename = "content")]
    pub content: Vec<models::MarkerDto>,
    #[serde(rename = "pageNumber")]
    pub page_number: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "totalItems")]
    pub total_items: i32,
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
}

impl MarkerDtoPage {
    pub fn new(
        content: Vec<models::MarkerDto>,
        page_number: i32,
        page_size: i32,
        total_items: i32,
        total_pages: i32,
    ) -> MarkerDtoPage {
        MarkerDtoPage {
            content,
            page_number,
            page_size,
            total_items,
            total_pages,
        }
    }
}
