/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkerGroup {
    #[serde(rename = "markers")]
    pub markers: Vec<models::MarkerTitle>,
    #[serde(rename = "name")]
    pub name: String,
}

impl MarkerGroup {
    pub fn new(markers: Vec<models::MarkerTitle>, name: String) -> MarkerGroup {
        MarkerGroup { markers, name }
    }
}
