/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MeasureCount {
    #[serde(rename = "MeasureCount_oneOf")]
    MeasureCountOneOf(Box<models::MeasureCountOneOf>),
    #[serde(rename = "MeasureCount_oneOf_1")]
    MeasureCountOneOf1(Box<models::MeasureCountOneOf1>),
}

impl Default for MeasureCount {
    fn default() -> Self {
        Self::MeasureCountOneOf(Default::default())
    }
}
