/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaddingType {
    #[serde(rename = "black")]
    Black,
    #[serde(rename = "blur")]
    Blur,
}

impl std::fmt::Display for PaddingType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Black => write!(f, "black"),
            Self::Blur => write!(f, "blur"),
        }
    }
}

impl Default for PaddingType {
    fn default() -> PaddingType {
        Self::Black
    }
}
