/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RandomizedClipOptions {
    #[serde(rename = "baseDuration")]
    pub base_duration: f64,
    #[serde(rename = "divisors")]
    pub divisors: Vec<f64>,
}

impl RandomizedClipOptions {
    pub fn new(base_duration: f64, divisors: Vec<f64>) -> RandomizedClipOptions {
        RandomizedClipOptions {
            base_duration,
            divisors,
        }
    }
}
