/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SongDto {
    #[serde(rename = "beats")]
    pub beats: Vec<f32>,
    #[serde(rename = "duration")]
    pub duration: f64,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "songId")]
    pub song_id: i64,
    #[serde(rename = "url")]
    pub url: String,
}

impl SongDto {
    pub fn new(
        beats: Vec<f32>,
        duration: f64,
        file_name: String,
        song_id: i64,
        url: String,
    ) -> SongDto {
        SongDto {
            beats,
            duration,
            file_name,
            song_id,
            url,
        }
    }
}
