/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StashConfig {
    #[serde(
        rename = "apiKey",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    #[serde(rename = "stashUrl")]
    pub stash_url: String,
}

impl StashConfig {
    pub fn new(stash_url: String) -> StashConfig {
        StashConfig {
            api_key: None,
            stash_url,
        }
    }
}
