/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StrokeType {
    StrokeTypeOneOf(Box<models::StrokeTypeOneOf>),
    StrokeTypeOneOf1(Box<models::StrokeTypeOneOf1>),
}

impl Default for StrokeType {
    fn default() -> Self {
        Self::StrokeTypeOneOf(Default::default())
    }
}
