/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StrokeTypeOneOf {
    #[serde(rename = "everyNth")]
    pub every_nth: Box<models::StrokeTypeOneOfEveryNth>,
}

impl StrokeTypeOneOf {
    pub fn new(every_nth: models::StrokeTypeOneOfEveryNth) -> StrokeTypeOneOf {
        StrokeTypeOneOf {
            every_nth: Box::new(every_nth),
        }
    }
}
