/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StrokeTypeOneOf1 {
    #[serde(rename = "accelerate")]
    pub accelerate: Box<models::StrokeTypeOneOf1Accelerate>,
}

impl StrokeTypeOneOf1 {
    pub fn new(accelerate: models::StrokeTypeOneOf1Accelerate) -> StrokeTypeOneOf1 {
        StrokeTypeOneOf1 {
            accelerate: Box::new(accelerate),
        }
    }
}
