/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// StrokeTypeOneOf1Accelerate : Steadily accelerates the strokes from `start_strokes_per_beat` to `end_strokes_per_beat`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StrokeTypeOneOf1Accelerate {
    #[serde(rename = "end_strokes_per_beat")]
    pub end_strokes_per_beat: f32,
    #[serde(rename = "start_strokes_per_beat")]
    pub start_strokes_per_beat: f32,
}

impl StrokeTypeOneOf1Accelerate {
    /// Steadily accelerates the strokes from `start_strokes_per_beat` to `end_strokes_per_beat`
    pub fn new(
        end_strokes_per_beat: f32,
        start_strokes_per_beat: f32,
    ) -> StrokeTypeOneOf1Accelerate {
        StrokeTypeOneOf1Accelerate {
            end_strokes_per_beat,
            start_strokes_per_beat,
        }
    }
}
