/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VideoSource {
    #[serde(rename = "Folder")]
    Folder,
    #[serde(rename = "Download")]
    Download,
    #[serde(rename = "Stash")]
    Stash,
}

impl std::fmt::Display for VideoSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Folder => write!(f, "Folder"),
            Self::Download => write!(f, "Download"),
            Self::Stash => write!(f, "Stash"),
        }
    }
}

impl Default for VideoSource {
    fn default() -> VideoSource {
        Self::Folder
    }
}
