/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoCleanupResponse {
    #[serde(rename = "deletedCount")]
    pub deleted_count: i32,
}

impl VideoCleanupResponse {
    pub fn new(deleted_count: i32) -> VideoCleanupResponse {
        VideoCleanupResponse { deleted_count }
    }
}
