/*
 * clip-mash
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.22.0-pre.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoDetailsDto {
    #[serde(rename = "markers")]
    pub markers: Vec<models::MarkerDto>,
    #[serde(rename = "video")]
    pub video: Box<models::VideoDto>,
}

impl VideoDetailsDto {
    pub fn new(markers: Vec<models::MarkerDto>, video: models::VideoDto) -> VideoDetailsDto {
        VideoDetailsDto {
            markers,
            video: Box::new(video),
        }
    }
}
