set shell := ["nu", "-c"]

default:
    @just --list

format:
    cargo +nightly fmt

check:
    cargo check
    cargo sqlx prepare --check
    cargo nextest run

start:
    cargo run 0.0.0.0

build:
    cargo build --release

setup:
    cargo install sqlx-cli
    sqlx migrate run

fix:
    cargo fix --allow-staged

generate-openapi-spec:
    cargo build
    cargo run --bin generate-openapi-spec ../api-docs.json
    
generate-rust-client:
    npx @openapitools/openapi-generator-cli generate -i ../api-docs.json -g rust -o ../rust-client
